/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import githubProjects from "@raina-ss/strapi-plugin-github-projects/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "github-projects": githubProjects,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
  },
});
